'use strict';

const { Schema, model } = require('mongoose');

const PAYMENT_PRODUCTS = ['subscription', 'boost', 'ad'];
const PAYMENT_STATUSES = ['initialized', 'verified', 'refunded', 'refund_failed'];

/**
 * One Chapa transaction, from `POST /payments/initialize-*` through
 * `GET /payments/verify-callback` and (for a rejected employer/agency
 * subscription) an eventual refund.
 *
 * Nothing persisted a payment record before this — `payment.routes.js`
 * talked to Chapa and flipped `verificationStatus`/`boostedUntil`
 * directly, with no row anywhere recording what was actually charged.
 * That's fine for "did this succeed", but it means there was nothing to
 * refund *from* when admin.service.js#rejectUser needed to send money
 * back — hence this model: `admin.service.js` looks up this user's most
 * recent verified `subscription` payment to know what to refund and via
 * which `txRef`.
 */
const paymentSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    role: {
      type: String,
      enum: ['employer', 'agency', 'seeker'],
      required: true,
    },
    // 'subscription' = employer/agency verification-tier payment;
    // 'boost' = seeker profile boost; 'ad' = employer/agency ad
    // placement (see ads.service.js). Same Chapa checkout flow, kept
    // in one collection since all three are "a Chapa transaction this
    // user made" — but only 'subscription' payments are ever refund
    // candidates (see admin.service.js).
    product: {
      type: String,
      enum: PAYMENT_PRODUCTS,
      required: true,
    },
    // Subscription tier ('basic'/'premium'/'enterprise') paid for.
    // null for boost/ad payments, which aren't tiered.
    plan: {
      type: String,
      default: null,
    },
    // The Ad this payment is for. null for every other product.
    adId: {
      type: Schema.Types.ObjectId,
      ref: 'Ad',
      default: null,
    },
    amount: {
      type: Number,
      required: true,
    },
    currency: {
      type: String,
      default: 'ETB',
    },
    // Chapa's transaction reference, generated by us at initialize time
    // (see TX_REF_PREFIX in payment.routes.js) and echoed back on the
    // verify-callback redirect.
    txRef: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    status: {
      type: String,
      enum: PAYMENT_STATUSES,
      default: 'initialized',
    },
    // Chapa's `data.ref_id` from a successful refund initiation —
    // stored so a stuck 'refund_failed' payment can be manually
    // reconciled against Chapa's dashboard/verify-refund endpoint later.
    chapaRefundReference: {
      type: String,
      default: null,
    },
    refundedAt: {
      type: Date,
      default: null,
    },
    // Free-text reason a refund was issued for — currently always the
    // admin's verification rejection reason (see admin.service.js).
    refundReason: {
      type: String,
      default: null,
    },
  },
  {
    timestamps: true,
  },
);

// admin.service.js#refundLatestSubscriptionPayment's lookup: "this
// user's most recent verified subscription payment".
paymentSchema.index({ userId: 1, product: 1, status: 1, createdAt: -1 });

paymentSchema.set('toJSON', {
  virtuals: true,
  transform: (_doc, ret) => {
    ret.id = ret._id.toString();
    delete ret._id;
    delete ret.__v;
    ret.userId = ret.userId.toString();
    if (ret.adId) ret.adId = ret.adId.toString();
    return ret;
  },
});

module.exports = model('Payment', paymentSchema);
module.exports.PAYMENT_PRODUCTS = PAYMENT_PRODUCTS;
module.exports.PAYMENT_STATUSES = PAYMENT_STATUSES;
